### ISSUE TITLE
BUMP ERROR?

### ISSUE THREAD

**Issue by sitxxar** [ducthanh98/airdrop#2]
I ran the bump script, but what came out was a query without any response
![image](https://github.com/ducthanh98/airdrop/assets/37711440/d3ecc2cd-efa6-4723-8a34-603f1a5babd8)

**Comment by ducthanh98** [comment]
I updated a new version. You can check it again

**Comment by doubleTroub1e** [comment]
hi, I also do have error with bump
<img width="810" alt="image" src="https://github.com/ducthanh98/airdrop/assets/18425295/b961bf43-71ce-4874-9f1d-016d27c3bc73">
also, as a suggestion: don't you want adding docker compose file like:
```
x-defaults:
  &default-service
  restart: unless-stopped
  stop_signal: SIGINT
  tty: true
  logging:
    driver: "json-file"
    options:
      max-size: 1m


services:
  gemz:
    <<: *default-service
    image: local:gemz_rasp4_20240620
    container_name: 'gemz'
    volumes:
      - ./gemz/query.txt:/app/query.txt  # Specific volume for gemz


  quackquack:
    <<: *default-service
    image: local:quackquack_rasp4_20240624
    container_name: 'quackquack'
    volumes:
      - ./quackquack/main.go:/root/main.go
      - ./quackquack/conf.toml:/root/conf.toml

  bump:
    <<: *default-service
    image: local:bump_rasp4_20240627
    container_name: 'bump'
    volumes:
      - ./bump/query.txt:/app/query.txt
      - ./bump/proxy.txt:/app/proxy.txt
``` 
guess adding query as ENV variable would  make it easier to work/update
FYI: I don't use proxy, so proxy file is empty 
PS: you can add some sample image of how to extract query like this 
<img width="1470" alt="image" src="https://github.com/ducthanh98/airdrop/assets/18425295/3757079a-fb9c-44c7-9b43-5920cc893945">
Also, making logs on English would make it simpler to use on any  market), but not crucial for those who really want to start it)
